### ISSUE TITLE
Header is vanished

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#10]
After checking out more than 8-9 times it shows error when i click on back button header is vanished.
![uploads/d5e54aa7-eb47-4bce-bf7f-eb67c23414d5/6.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd5e54aa7-eb47-4bce-bf7f-eb67c23414d5%2F6.png)

**Comment by codeyash** [comment]
Working on solution for this.

**Comment by codeyash** [comment]
Fixed
