### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#11]
On home page screen product images missing
![uploads/7eafc962-ea06-4278-b469-69203b78fafa/7_Missing_images.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7eafc962-ea06-4278-b469-69203b78fafa%2F7_Missing_images.png)

**Comment by codeyash** [comment]
It's not a bug but feature.

You can skip image for any sale item.
