### ISSUE TITLE
Guest checkout error

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#14]
This error is shown FopUser has no profile. While Checkingout as guest user 
![uploads/11a99df6-dae7-4d8c-8da9-f0e09bcab7e1/Guest checkout error.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F11a99df6-dae7-4d8c-8da9-f0e09bcab7e1%2FGuest+checkout+error.png)

**Comment by codeyash** [comment]
Please test.

**Comment by codeyash** [comment]
I'm closing. If coming reopen it.

**Comment by codeyash** [comment]
We have fixed it using catching exception. It was coming of very old email used. But now fixed for all such cases
