### ISSUE TITLE
Yello page error on registration page

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#15]
After placing a order and register with a new email id, completing the registration process it shows yellow page error

**Comment by codeyash** [comment]
On missing email we need handle it. It may need more time than we have.

**Comment by codeyash** [comment]
Handled :)

**Comment by vbvinay** [comment]
Completing the registration process it shows yellow page error

**Comment by codeyash** [comment]
Please share yellow image on mail

**Comment by codeyash** [comment]
Fixed the error.
Please test.
