### ISSUE TITLE
Register form field unclickable

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#181]
On Navigation, when we mouse hover on My Profile icon, on registration screen Register form field 'unclickable'.(Email, password & confirm pas
![untitled](https://cloud.githubusercontent.com/assets/25278537/25122501/cba1c6ae-2442-11e7-97af-c219b6811307.png)
sword.)

**Comment by codeyash** [comment]
Fixed

**Comment by codeyash** [comment]
Done
