### ISSUE TITLE
ALPACA: UI Color Change Requests 4-25-2017

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#190]
Please update as follows:

Header Background: White
Header Text: Alpaca Grey (#58585b)

Body Area:
Section Header Background: Alpaca Grey (#58585b)
Section Header Text: Alpaca Yellow (#f7ec37)
Menu Item Name Text: Alpaca Grey (#58585b)
Menu Item Description Text:  Alpaca Grey (#58585b)

**Comment by codeyash** [comment]
Please confirm this is what  you are asking

https://eatstax.com/alpaca-raleigh/modern/

If not please provide a screenshot with the color code so that I can create exact look.

**Comment by grethapouza** [comment]
Thanks Yash, not exactly, please see attached with my perception of the request.
![fop_issue_190](https://cloud.githubusercontent.com/assets/27704798/25529702/3041144c-2bf1-11e7-9f73-3942c25eacc8.png)

**Comment by codeyash** [comment]
Pls review now

https://eatstax.com/alpaca-raleigh/modern/

**Comment by grethapouza** [comment]
Looks great, one more update :)

See attached.

Best,

Gretha Pouza
*VP Operations*
SAM IT Solutions
p: 919.800.0044  m: 919.890.0543
a: 15100 Weston Parkway #204, Cary, NC 27513
w: www.samitsolutions.com  e: gretha@samitsolutions.com
<https://www.facebook.com/SamAnalytic/>
<https://www.linkedin.com/company/577955?trk=vsrp_companies_cluster_name&trkInfo=VSRPsearchId%3A2978210991481772931150%2CVSRPtargetId%3A577955%2CVSRPcmpt%3Acompanies_cluster>

CONFIDENTIALITY NOTICE: This e-mail message and any attachments are for the
sole use of the intended recipient(s) and may contain proprietary,
confidential, trade secret or privileged information. Any unauthorized
review, use, disclosure or distribution is prohibited and may be a
violation of law. If you are not the intended recipient or a person
responsible for delivering this message to an intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message and any attachments.

**Comment by codeyash** [comment]
No attachments :(

Pls send mail or attach here :)

**Comment by grethapouza** [comment]
Do you see it now? Also updating github now.

Best,

Gretha Pouza
*VP Operations*
SAM IT Solutions
p: 919.800.0044  m: 919.890.0543
a: 15100 Weston Parkway #204, Cary, NC 27513
w: www.samitsolutions.com  e: gretha@samitsolutions.com
<https://www.facebook.com/SamAnalytic/>
<https://www.linkedin.com/company/577955?trk=vsrp_companies_cluster_name&trkInfo=VSRPsearchId%3A2978210991481772931150%2CVSRPtargetId%3A577955%2CVSRPcmpt%3Acompanies_cluster>

CONFIDENTIALITY NOTICE: This e-mail message and any attachments are for the
sole use of the intended recipient(s) and may contain proprietary,
confidential, trade secret or privileged information. Any unauthorized
review, use, disclosure or distribution is prohibited and may be a
violation of law. If you are not the intended recipient or a person
responsible for delivering this message to an intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message and any attachments.

**Comment by grethapouza** [comment]
Please find the attachment here:
![2017-04-28_1055](https://cloud.githubusercontent.com/assets/27704798/25534669/81a61466-2c02-11e7-92dc-3ae42cb685e9.png)

**Comment by codeyash** [comment]
Done.

I'm closing. If required please reopen.
