### ISSUE TITLE
ALPACA: Update Menu Prices

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#191]
Please update the menu prices as seen attached.

[Alpaca2017TOGO.pdf](https://github.com/samitsolutions/fop/files/959352/Alpaca2017TOGO.pdf)

**Comment by codeyash** [comment]
We've updated all prices except below items.

Special item prices are missing.

**Comment by codeyash** [comment]
If any more price updated needed please open a new issue.

PDF work is matched and updated.
