### ISSUE TITLE
ALPACA: Logo cut off in header

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#193]
Device: iPhone 6s
Version: 10.3.1
Browser: Safari (latest version as found within 10.3.1 iPhone iOS)

**Replication Steps:**
1. Navigate to https://eatstax.com/alpaca-raleigh, the logo is cut off in the header.

**Screenshot:**
![2017-04-26](https://cloud.githubusercontent.com/assets/27704798/25450687/ad9190c6-2a8d-11e7-9a61-c7b3132f2a66.jpg)

**Comment by codeyash** [comment]
Logo will be squeezed and hard to see/understand. 

See their official website. It's like above. It's a square logo. We can't force to fit in bar.

I'm closing this. Please reopen if required.
