### ISSUE TITLE
ALPACA: After Adding Item to Cart, "Add to Cart" button does not revert back to menu

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#194]
Device: iPhone 6s
Version: 10.3.1
Browser: Safari (latest version as found within 10.3.1 iPhone iOS)

**Replication Steps:**
1. Navigate to https://eatstax.com/alpaca-raleigh.
2. Add an item to the cart, click "Add to Cart" (scroll to the very end).

**Issue:**
After the user clicks on the "Add to Cart" button, the user is not revert back to the menu. In order to go back to the menu, the user has to click on "Continue Shopping" in order to add more menu items to the cart.

**Comment by codeyash** [comment]
This is not a bug.

This is by design.

You can suggest what you here.

Adding items and taking back user to main page will confuse user. 

Let's discuss on this

**Comment by grethapouza** [comment]
Hi Yash,

Yes, you are absolutely right, this should be closed.
