### ISSUE TITLE
Zayka: Two Pages are printing (Cloud to kitchen to print)

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#195]
Two page are printing, one blank page and then one content page. Please only have the content (aka order) page print only.

**Comment by codeyash** [comment]
Either this is problem in fax machine or RingCentral.  

Ask Dolly/Keshav to setup fax machine properly. PDF contains only one page.

I can debug more on RC end but before that make sure fax machine settings are correct.

**Comment by codeyash** [comment]
Please follow up with Dolly.

**Comment by grethapouza** [comment]
Thanks Yash, I have sent this Dolly, we can close it.
