### ISSUE TITLE
ALPACA: Please add missing images to food products

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#196]
https://www.dropbox.com/sh/zuud0za9u7xo84q/AAASXea0mCm0v6g7C1ECSnP7a?dl=0

**Comment by grethapouza** [comment]
PLEASE HOLD ON THIS REQUEST UNTIL FURTHER NOTICE FROM ME.

**Comment by codeyash** [comment]
Should I work on this? You removed the label.

**Comment by grethapouza** [comment]
Hi Yash,

Yes, but the only non-duplicates are Cole Slaw and Chicken Soup, those can
be added. For the rest we are still pendings images, emailing client now.

Best,

Gretha Pouza
*VP Operations*
SAM IT Solutions
p: 919.800.0044  m: 919.890.0543
a: 15100 Weston Parkway #204, Cary, NC 27513
w: www.samitsolutions.com  e: gretha@samitsolutions.com
<https://www.facebook.com/SamAnalytic/>
<https://www.linkedin.com/company/577955?trk=vsrp_companies_cluster_name&trkInfo=VSRPsearchId%3A2978210991481772931150%2CVSRPtargetId%3A577955%2CVSRPcmpt%3Acompanies_cluster>

CONFIDENTIALITY NOTICE: This e-mail message and any attachments are for the
sole use of the intended recipient(s) and may contain proprietary,
confidential, trade secret or privileged information. Any unauthorized
review, use, disclosure or distribution is prohibited and may be a
violation of law. If you are not the intended recipient or a person
responsible for delivering this message to an intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message and any attachments.

**Comment by codeyash** [comment]
I will wait for all pictures.

**Comment by grethapouza** [comment]
Client does not know when he will have them, has requested that we implement this for the time being instead. Probably a discussion which should be had.... how many hours of support per month or quarter should be included in the nominal fee we are charging for this service.

Kind regards,
Gretha Pouza 

(Sent from my iPhone, please excuse any typos)

**Comment by grethapouza** [comment]
We have unlimited support, as long as it is within reason.
S

**Comment by codeyash** [comment]
Added placeholder, slaw and soup images.

Please open a new ticket for new images.
