### ISSUE TITLE
ALPACA: After Adding Item to Cart, "Add to Cart" button does not scroll up item summary selection.

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#198]
Device: iPhone 6s
Version: 10.3.1
Browser: Safari (latest version as found within 10.3.1 iPhone iOS)

Replication Steps:
1. Navigate to https://eatstax.com/alpaca-raleigh.
2. Add an item to the cart, click "Add to Cart".
3. Add side items, drinks, etc, then scroll to the very end of the "menu item detailed selection view" and click "Add to Cart".

Issue:
After the user clicks on the "Add to Cart" button, the view does not automatically scroll up showing the two options for the user to select ("Checkout" and "Continue Shopping"), this is how it functions on the Android platform.

**Comment by codeyash** [comment]
Question: It works on a desktop, why doesn't this work on mobile?

$('html').scrollTop({scrollTop: 0, 0);
Answer: Because html isn't being treated as a DOM node.

$('body').scrollTop({scrollTop: 0, 0);
Always the body, never the html.


This fixed our problem

**Comment by grethapouza** [comment]
Hi Yash,

I just tested and it still did not auto scroll up. Please advise.

**Comment by codeyash** [comment]
It was not pushed on Live.

Now it is.

Please test again.

**Comment by codeyash** [comment]
It's not working perfectly. Let me dig more on this. :(

**Comment by grethapouza** [comment]
Thanks Yash,

I just tested and it did not work, was going to clear history and restart
phone. Holding for further instruction.

Best,

Gretha Pouza
*VP Operations*
SAM IT Solutions
p: 919.800.0044  m: 919.890.0543
a: 15100 Weston Parkway #204, Cary, NC 27513
w: www.samitsolutions.com  e: gretha@samitsolutions.com
<https://www.facebook.com/SamAnalytic/>
<https://www.linkedin.com/company/577955?trk=vsrp_companies_cluster_name&trkInfo=VSRPsearchId%3A2978210991481772931150%2CVSRPtargetId%3A577955%2CVSRPcmpt%3Acompanies_cluster>

CONFIDENTIALITY NOTICE: This e-mail message and any attachments are for the
sole use of the intended recipient(s) and may contain proprietary,
confidential, trade secret or privileged information. Any unauthorized
review, use, disclosure or distribution is prohibited and may be a
violation of law. If you are not the intended recipient or a person
responsible for delivering this message to an intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message and any attachments.

**Comment by codeyash** [comment]
Please retest. I tried with some other option this time. On Safari showing fixed but on the simulator it's failing.

**Comment by grethapouza** [comment]
Hi Yash, I just tested and was able to replicate the issue.

**Comment by codeyash** [comment]
Possible solutions:

- http://luxiyalu.com/playground/overlay/
- http://blog.christoffer.me/six-things-i-learnt-about-ios-safaris-rubber-band-scrolling/

Let me keep digging 

Keep you posted

**Comment by codeyash** [comment]
An alternate is implemented in #230 
Pushed on Dev

Please review

**Comment by codeyash** [comment]
Fixed
