### ISSUE TITLE
Completion  page

### ISSUE THREAD

**Issue by codeyash** [samitsolutions/fop#204]
Consider this as a good sample for the order completion/checkout page. Get Directions can be useful for some. After the wording "Carryout From", it should read the restaurant name in the next line. 
![Preview Image Checkout](https://cloud.githubusercontent.com/assets/654242/25579257/eab38a40-2e93-11e7-8906-3f6c13071d25.png)

**Comment by codeyash** [comment]
Hello Gretha,

Please provide the correct message on left screen. Below is relevant content:

### Your order is received
Check your invoice email for your ordered items

**Comment by codeyash** [comment]
- Need a setting for this
-Custom HTML message per restaurants 
- Default message

**Comment by grethapouza** [comment]
Hi Yash,

Can we please replicate what you have as an example?

Instead of:
"Check your confirmation email for your estimated order ready time."

Please replace with:
"Check your email for your invoice for your ordered items."

**Comment by codeyash** [comment]
It's under progress. Right now it's static message in HTML. I will make it a setting with a default message which can be changed per location.

**Comment by codeyash** [comment]
Pushed to dev

**Comment by codeyash** [comment]
Live
