### ISSUE TITLE
ALPACA: Specific, Whole Chicken menu item changes

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#207]
Changes as defined below and per attached screenshot would be shown when a user clicks on "Add to Cart" button for the Whole Chicken menu item only.

Chicken Cut	 4 Pieces 
 8 Pieces

Choose Chicken	 Includes white and dark meat
 All dark meat
 All white meat (+ $1.00)

 Pick 2 Sides	 White Rice
 Black Beans
 House Salad with Ranch Dressing
 House Salad with Italian Dressing
 House Salad with Cilantro Vinaigrette Dressing
 Coleslaw
 Hand Cut Fries
 Chicken Soup
 Yellow Corn
 Rice Topped with Black Beans (+ $0.50)
 Green Beans (+ $0.50)
 Steamed Yuca with Garlic Mojo Sauce (+ $0.50)
 Yucca Fries (+ $0.50)
 Tostones (+ $0.50)
 Maduros (+ $0.50)

Pick 4 Sauces	 1 Oz Yellow Dipping Sauce 
 1 Oz Green Dipping Sauce 
 1 Oz Extra Yellow Dipping Sauce 
 1 Oz Extra Green Dipping Sauce  

Add	 8 Oz Yellow Dipping Sauce (+ $2.50)
 8 Oz Green Dipping Sauce (+ $2.50)
 12 Oz Yellow Dipping Sauce (+ $3.50)
 12 Oz Green Dipping Sauce (+ $3.50)
 4 Tortillas (+ $1.00) 

Drinks	 Sweet Tea (+ $1.95)
 Fountain Drink (+ $1.95)
 Specialty Drink (+ $2.25)
 Chi Cha Morada (+ $2.25)
 Inca Kola Can (+ $1.50) 

House Desserts	 Caramel Flan (+ $2.49)
 Alfajores (+ $1.95)
 Tres Leches (+ $2.99) 

[Whole Chicken CR.docx](https://github.com/samitsolutions/fop/files/968494/Whole.Chicken.CR.docx)

**Comment by codeyash** [comment]
Done

Please review

**Comment by grethapouza** [comment]
Hi Yash,

Please review the attached word document in the original request, we are
missing an option under "Choose Chicken", 4 pieces should appear before 8
pieces (also, 4 should be default), pricing needs to be updated (as well as
for consistency of formatting across all item selections, i.e from $2.5 to
$2.50)

Best,

Gretha Pouza
*VP Operations*
SAM IT Solutions
p: 919.800.0044  m: 919.890.0543
a: 15100 Weston Parkway #204, Cary, NC 27513
w: www.samitsolutions.com  e: gretha@samitsolutions.com
<https://www.facebook.com/SamAnalytic/>
<https://www.linkedin.com/company/577955?trk=vsrp_companies_cluster_name&trkInfo=VSRPsearchId%3A2978210991481772931150%2CVSRPtargetId%3A577955%2CVSRPcmpt%3Acompanies_cluster>

CONFIDENTIALITY NOTICE: This e-mail message and any attachments are for the
sole use of the intended recipient(s) and may contain proprietary,
confidential, trade secret or privileged information. Any unauthorized
review, use, disclosure or distribution is prohibited and may be a
violation of law. If you are not the intended recipient or a person
responsible for delivering this message to an intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message and any attachments.

**Comment by codeyash** [comment]
Data entry is corrected.

Precision requires a code change and I'm working on that. I will open that as a new issue.

Please review and close.

**Comment by codeyash** [comment]
Closing. Please reopen if required.
