### ISSUE TITLE
ALPACA: Specific, Arroz Chaufa menu item changes

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#208]
Please update the Arroz Chaufa menu item to include the following:

![arroz-chaufa](https://cloud.githubusercontent.com/assets/27704798/25592788/13f65fba-2e88-11e7-9a0f-9a6150b7fc82.png)

Please remove the extra negative space (which I have in my image). Essentially we want it work the same as for the "Steak Salad" menu item.

**Comment by codeyash** [comment]
Dressings item is added.

I can't see what negative space. Please explain/review.

**Comment by grethapouza** [comment]
Looks perfect (what you completed). This task is completed.

**Comment by codeyash** [comment]
Thanks
