### ISSUE TITLE
ALPACA: COMMON menu item changes

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#209]
Please update this in all places with similar views:
[Common Changes.docx](https://github.com/samitsolutions/fop/files/968654/Common.Changes.docx)

Exceptions for the above (meaning that only the Pick 2 Sauces must be added, the rest can excluded):
- All Made to Order Plates

Excluded from all of the above changes:
Sides
Desserts
Drinks

p.s. Whole Chicken has 4 sauces, not 2 is the only difference, this has its own issue associated.

**Comment by codeyash** [comment]
MADE TO ORDER PLATES Please allow additional time as plates are made fresh.

This Is unique and doesn't contain any sauces.

Combos Category contains sauces requirement and we've completed that.

Let's have a quick call on this.

**Comment by codeyash** [comment]
Please suggest.

**Comment by codeyash** [comment]
Gentle reminder :)

**Comment by grethapouza** [comment]
Hi Yash,

This is new request, creating separate ticket. We need to add sauce options for the made to order plates.

**Comment by codeyash** [comment]
Okay. Closed
