### ISSUE TITLE
ALPACA: Update Chicken Salad Description

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#210]
Update Chicken Salad Description as follows

Ranch, Italian or Cilantro Vinaigrette. House salad topped with boneless sliced rotisserie chicken, sliced tomatoes, sliced cucumbers, queso fresco and hard boiled eggs.

**Comment by codeyash** [comment]
Done

**Comment by grethapouza** [comment]
Nice job! Thank you.

Best,

Gretha Pouza
*VP Operations*
SAM IT Solutions
p: 919.800.0044  m: 919.890.0543
a: 15100 Weston Parkway #204, Cary, NC 27513
w: www.samitsolutions.com  e: gretha@samitsolutions.com
<https://www.facebook.com/SamAnalytic/>
<https://www.linkedin.com/company/577955?trk=vsrp_companies_cluster_name&trkInfo=VSRPsearchId%3A2978210991481772931150%2CVSRPtargetId%3A577955%2CVSRPcmpt%3Acompanies_cluster>

CONFIDENTIALITY NOTICE: This e-mail message and any attachments are for the
sole use of the intended recipient(s) and may contain proprietary,
confidential, trade secret or privileged information. Any unauthorized
review, use, disclosure or distribution is prohibited and may be a
violation of law. If you are not the intended recipient or a person
responsible for delivering this message to an intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message and any attachments.
