### ISSUE TITLE
 Coupon code loading error

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#216]
Steps:
1. Navigate to 

http://dev.eatstax.com/manage/coupon/list.

2. In admin panel click manage coupon Create new coupon and select percentage discount in type, then type user limit 1 click add button.

3. Navigate to http://dev.eatstax.com/vin.

4.Add an item to the cart, click "Add to Cart" and click "checkout", then apply coupon code.

Issue:
After the user clicks on the "apply coupon" button, 
its show loading in button.

![cart summary eatstax](https://cloud.githubusercontent.com/assets/25278537/25650717/82cc7eae-2ffc-11e7-9b19-15695c2d81fc.png)

**Comment by codeyash** [comment]
Not able to reproduce it.

Please retest it now

**Comment by codeyash** [comment]
- Open firebug
- Click clear (red icon button)
- Apply coupon
- Url will produce 500 error if failed
- Click on it and copy the error from it

**Comment by codeyash** [comment]
Related code patched to the system based on exception logs. Pushed.

Please open a new issue if happens again.

Live and Fixed.
