### ISSUE TITLE
Error in guest checkout

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#217]
- Add an item to the cart
- Click checkout button
- Checkout by Guest Checkout
If user checkout as a guest user, after checkout process when user place order.

Now 500 error comes i.e. shows yellow page error

**Comment by codeyash** [comment]
Because there is not stripe key

Again you missed format style. Please follow format strictly. It will be hard to track where is error dev or production.

**Comment by codeyash** [comment]
Closed
