### ISSUE TITLE
ALPACA: Whole Chicken combo, missing "Choose Chicken" option

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#227]
Whole Chicken combo, missing "Choose Chicken" option

Option missing:

Includes white and dark meat

This option should be the default selection.

![issue_227](https://cloud.githubusercontent.com/assets/27704798/25723714/2be0ee40-30e7-11e7-8e9b-4684752e7662.png)

**Comment by codeyash** [comment]
Done
