### ISSUE TITLE
ALPACA: Sweet tea pricing typo

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#228]
Please update the sweet tea price to $1.95

**Comment by codeyash** [comment]
It's already 1.95..Am I missing something here?

**Comment by grethapouza** [comment]
Hmmm, it's showing as 1.75 from my phone:



Kind regards,
Gretha Pouza 

(Sent from my iPhone, please excuse any typos)

**Comment by codeyash** [comment]
Please refresh.

It's 1.95. I haven't changed anything. Let me know which location you're facing this although items are common in all locations.

A screenshot, please.

**Comment by grethapouza** [comment]
Hi Yash,

I refreshed and checked in incognito and still price as 1.75, please advise if there is an alternative method through which I should check.

Replication steps:
Once browsing the https://eatstax.com/alpaca-raleigh/, add any menu item which has an option to add a drink (i.e. 1/4 chicken - Dark Meat), scroll down to drinks, here you will sweet tea price as being 1.75, it should be 1.95).

![issue_228](https://cloud.githubusercontent.com/assets/27704798/25804641/b408e4a4-33ca-11e7-9da8-1587d5793632.png)

**Comment by codeyash** [comment]
Fixed

My bad. I was checking items and not line items.
