### ISSUE TITLE
ALPACA: Not able to scroll down on order summary checkout view

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#229]
Device: iPhone 6s
Version: 10.3.1
Browser: Safari (latest version as found within 10.3.1 iPhone iOS)

Replication Steps:

1. Navigate to https://eatstax.com/alpaca-raleigh.
2. Add an item to the cart, click "Add to Cart" (scroll to the very end).
2. Scroll back up and click checkout.
Issue:
After the user clicks on the "Checkout" button, the user is taken to the "checkout - order summary review" view, but I am not able to scroll to see my entire order.

**Comment by codeyash** [comment]
Please attach screenshots and videos. I don't have the device and it's impossible to visual what's the error.

**Comment by grethapouza** [comment]
Thanks Yash, will do, though now I'm not able to replicate it again... let me see what I can do to provide more useful information.

Kind regards,
Gretha Pouza 

(Sent from my iPhone, please excuse any typos)

**Comment by codeyash** [comment]
Please reopen if faces issues again.
