### ISSUE TITLE
Show Cart Value by default 1

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#48]
The value of cart is by default 1.
![uploads/7d544d16-e31b-432f-84de-013bf2a6c0f6/Cart Show 1 no.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7d544d16-e31b-432f-84de-013bf2a6c0f6%2FCart+Show+1+no.png)

**Comment by codeyash** [comment]
What do you mean?

**Comment by vbvinay** [comment]
If i open a front panel by default item notification 1 is there at cart icon but it contains no item .

**Comment by codeyash** [comment]
Okay. Got it.

**Comment by codeyash** [comment]
Now its working perfectly.

Can you please tell me when / how we can produce this issue.

**Comment by codeyash** [comment]
I got the reason.

Adding cart from one restro and viewing other restro in same time period will create such problems.

For now it's supported as this is a dedicated platform for one restro

**Comment by codeyash** [comment]
Fixed
