### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#6]
Error while login with facebook and twitter.

**Comment by codeyash** [comment]
Key was not configured. Now I created new apps. 
#4 fixed this.

**Comment by vbvinay** [comment]
App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.
Facebook login not working.

**Comment by codeyash** [comment]
Now try. I marked app public.

**Comment by codeyash** [comment]
It seems we need to submit app and get it reviewed.

https://developers.facebook.com/docs/facebook-login/review/requirements

for that we need to prepare some data like privacy policy and terms of use And app icon etc

**Comment by codeyash** [comment]
Please test

**Comment by vbvinay** [comment]
When i logged in facebook then yellow page error occurred after that.

**Comment by codeyash** [comment]
Image please

**Comment by codeyash** [comment]
Its a rare scenario like same user wants to use multiple login methods. 
Each profile make a new user but user with same email like facebook account, gmail account and now try to use these methods to login. Boom.

We need to handle if we already have same email in system.

**Comment by codeyash** [comment]
If possible please test with other facebook acounts. Create few facebook accounts to test it. I want to be sure it's duplicate email problem.

**Comment by codeyash** [comment]
For now closing this. Please report new issue if still coming with detailed info
