### ISSUE TITLE
Button not working

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#7]
Sometime continue shopping button doesn't work.
![uploads/c8152aa9-2867-4b52-b298-80cd9a0ff521/3_Not clickable Continue shopping.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc8152aa9-2867-4b52-b298-80cd9a0ff521%2F3_Not+clickable+Continue+shopping.png)

**Comment by codeyash** [comment]
Its was not working when we were on full page layout as it was just closing popup. 
Now I added two separate feature for that button and now it should work properly.
